name: Shell-Linter

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  Shell-Linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: azohra/shell-linter@latest
        with:
          path: "*.ebuild"
          exclude-paths: "opencv, pillow, numpy"
